// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ticket/FuelTicket.tsx": () => import("../components/mockups/ticket/FuelTicket.tsx"),
  "./components/mockups/tma-variants/DarkNeon.tsx": () => import("../components/mockups/tma-variants/DarkNeon.tsx"),
  "./components/mockups/tma-variants/DeepField.tsx": () => import("../components/mockups/tma-variants/DeepField.tsx"),
  "./components/mockups/tma-variants/FeedStream.tsx": () => import("../components/mockups/tma-variants/FeedStream.tsx"),
  "./components/mockups/tma-variants/LiquidGlass.tsx": () => import("../components/mockups/tma-variants/LiquidGlass.tsx"),
  "./components/mockups/tma-variants/OperatorHUD.tsx": () => import("../components/mockups/tma-variants/OperatorHUD.tsx"),
  "./components/mockups/tma-variants/PanicButton.tsx": () => import("../components/mockups/tma-variants/PanicButton.tsx"),
  "./components/mockups/tma-variants/ProximityList.tsx": () => import("../components/mockups/tma-variants/ProximityList.tsx"),
  "./components/mockups/tma-variants/RefinedSignal.tsx": () => import("../components/mockups/tma-variants/RefinedSignal.tsx")
};
